//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_GiveAidProEntities1 : DbContext
    {
        public db_GiveAidProEntities1()
            : base("name=db_GiveAidProEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_About> tbl_About { get; set; }
        public virtual DbSet<tbl_Activity> tbl_Activity { get; set; }
        public virtual DbSet<tbl_Donation> tbl_Donation { get; set; }
        public virtual DbSet<tbl_DonationCause> tbl_DonationCause { get; set; }
        public virtual DbSet<tbl_DonationCauseNGO> tbl_DonationCauseNGO { get; set; }
        public virtual DbSet<tbl_Gallery> tbl_Gallery { get; set; }
        public virtual DbSet<tbl_IntrestActivities> tbl_IntrestActivities { get; set; }
        public virtual DbSet<tbl_NGO> tbl_NGO { get; set; }
        public virtual DbSet<tbl_OurAchievements> tbl_OurAchievements { get; set; }
        public virtual DbSet<tbl_Partner> tbl_Partner { get; set; }
        public virtual DbSet<tbl_Position> tbl_Position { get; set; }
        public virtual DbSet<tbl_QnA> tbl_QnA { get; set; }
        public virtual DbSet<tbl_TeamMember> tbl_TeamMember { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_UserType> tbl_UserType { get; set; }
    }
}
