//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_About
    {
        public int PK_ID { get; set; }

        [Required, MaxLength(2500, ErrorMessage = "What we do section must not exceed from 2500 charecters"), DataType(DataType.MultilineText), Display(Name ="What We Do")]
        public string What_We_Do { get; set; }

        [Required, MaxLength(2500, ErrorMessage = "Our Mission section must not exceed from 2500 charecters"), DataType(DataType.MultilineText), Display(Name = "Our Mission")]
        public string Our_Mission { get; set; }

        [Required, MaxLength(2500, ErrorMessage = "Career with us section must not exceed from 2500 charecters"), DataType(DataType.MultilineText), Display(Name = "Career With Us")]
        public string Career_With_Us { get; set; }

        [Required, MaxLength(2500, ErrorMessage = "About Us section must not exceed from 2500 charecters"), DataType(DataType.MultilineText), Display(Name = "About Us")]
        public string About_Us { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
