//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DonationCauseNGO
    {
        public int PK_ID { get; set; }
        public Nullable<int> FK_DonationCause { get; set; }
        public Nullable<int> FK_NGO { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual tbl_DonationCause tbl_DonationCause { get; set; }
        public virtual tbl_NGO tbl_NGO { get; set; }
    }
}
