//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_DonationCause
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DonationCause()
        {
            this.tbl_Donation = new HashSet<tbl_Donation>();
            this.tbl_DonationCauseNGO = new HashSet<tbl_DonationCauseNGO>();
            this.tbl_NGO = new HashSet<tbl_NGO>();
        }
    
        public int PK_ID { get; set; }

        [Required, MaxLength(50, ErrorMessage ="Donation Cause Name must not exceed from 50 charecters"), DataType(DataType.Text), Display(Name = "Donation Cause Name")]
        public string DonationCauseName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }

        [MaxLength(980, ErrorMessage = "Pictue name not exceed from 980 charecters"), DataType(DataType.Text), Display(Name = "Picture")]
        public string Picture { get; set; }

        [Required, MaxLength(2500, ErrorMessage = "Description must not exceed from 2500 charecters"), DataType(DataType.Text)]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Donation> tbl_Donation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DonationCauseNGO> tbl_DonationCauseNGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_NGO> tbl_NGO { get; set; }
    }
}
