//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_NGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_NGO()
        {
            this.tbl_Donation = new HashSet<tbl_Donation>();
            this.tbl_DonationCauseNGO = new HashSet<tbl_DonationCauseNGO>();
        }
    
        public int PK_ID { get; set; }

        [Required, MaxLength(50, ErrorMessage = "NGO name must not exceed from 50 charecters"), DataType(DataType.Text), Display(Name = "NGO Name")]
        public string NGOName { get; set; }

        [EmailAddress, Required, MaxLength(50, ErrorMessage = "Email must not exceed from 50 charecters"), DataType(DataType.EmailAddress), Display(Name = "Email")]
        public string Email { get; set; }

        [MaxLength(980, ErrorMessage ="Logo name must not exceed from 980 charecters"), Display(Name = "Logo")]
        public string Logo { get; set; }

        [DataType(DataType.PhoneNumber), MaxLength(50, ErrorMessage ="Invalid Phone Number"),  Phone, Display(Name = "Phone")]
        public string Phone { get; set; }

        [Url, DataType(DataType.Url), MaxLength(50, ErrorMessage ="Website URL is invalid"), Display(Name = "Website")]
        public string Website { get; set; }
        public Nullable<int> Fk_DonationCause { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Donation> tbl_Donation { get; set; }
        public virtual tbl_DonationCause tbl_DonationCause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DonationCauseNGO> tbl_DonationCauseNGO { get; set; }
    }
}
