//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Position()
        {
            this.tbl_TeamMember = new HashSet<tbl_TeamMember>();
        }
    
        public int PK_ID { get; set; }

        [Required, DataType(DataType.Text), MaxLength(50, ErrorMessage = "Position name must not exceed 50 characters"), Display(Name = "Position Name")]
        public string PositionName { get; set; }

        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TeamMember> tbl_TeamMember { get; set; }
    }
}
