//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Activity
    {
        public int PK_ID { get; set; }

        [Required, DataType(DataType.Text), MaxLength(50, ErrorMessage ="Title must not exceed from 50 charecters"), Display(Name = "Title")]
        public string Title { get; set; }

        [Required, DataType(DataType.Text), MaxLength(2500, ErrorMessage = "Title must not exceed from 2500 charecters"), Display(Name = "Decscription")]
        public string Description { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }

        [DataType(DataType.Text), MaxLength(980, ErrorMessage = "Picture name must not exceed from 980 charecters"), Display(Name = "Picture")]
        public string Picture { get; set; }
    }
}
