//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_Donation = new HashSet<tbl_Donation>();
            this.tbl_IntrestActivities = new HashSet<tbl_IntrestActivities>();
            this.tbl_QnA = new HashSet<tbl_QnA>();
        }
    
        public int PK_ID { get; set; }
        [Required, DataType(DataType.Text), MaxLength(50, ErrorMessage = "Full name must not exceed 50 charecters"), Display(Name = "Full Name")]
        public string FullName { get; set; }
        [DataType(DataType.Text), MaxLength(980, ErrorMessage = "Picture name must not exceed 980 charecters"), Display(Name = "Picture")]
        public string Picture { get; set; }
        [Required, DataType(DataType.EmailAddress), MaxLength(50, ErrorMessage = "Email must not exceed 50 charecters"), EmailAddress, Display(Name = "Email Adress")]
        public string Email { get; set; }
        [Required, DataType(DataType.Password), MaxLength(50, ErrorMessage = "Password must not exceed 50 charecters"), Display(Name = "Password")]
        public string Password { get; set; }
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        public Nullable<int> FK_UserType { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Donation> tbl_Donation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_IntrestActivities> tbl_IntrestActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QnA> tbl_QnA { get; set; }
        public virtual tbl_UserType tbl_UserType { get; set; }
    }
}
