//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_QnA
    {
        public int PK_ID { get; set; }
        public Nullable<int> FK_User { get; set; }

        [DataType(DataType.MultilineText), MaxLength(2500, ErrorMessage ="Question must not exceed 2500 charecters"), Display(Name = "Question")]
        public string Question { get; set; }

        [DataType(DataType.MultilineText), MaxLength(2500, ErrorMessage = "Answer must not exceed 2500 charecters"), Display(Name = "Answer")]
        public string Answer { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
