//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveAid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Gallery
    {
        public int PK_ID { get; set; }

        [DataType(DataType.Text), MaxLength(980, ErrorMessage = "Picture name must not exceed from 980"), Display(Name = "Picture")]
        public string Picture { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }

        [DataType(DataType.Text), MaxLength(50, ErrorMessage = "Title must not exceed from 50"), Display(Name = "Title")]
        public string Title { get; set; }
    }
}
